Added Upload and DOwnload actions

diff --git a/.github/workflows/ascii-artwork.yml b/.github/workflows/ascii-artwork.yml
--- a/.github/workflows/ascii-artwork.yml
+++ b/.github/workflows/ascii-artwork.yml
@@ -1,5 +1,4 @@
 name: generate ascii Artwork
-
 on:
   push
 
@@ -13,35 +12,35 @@ jobs:
     - name: Execute cowsay CMD
       run: cowsay -f dragon "RUN for cover, I'm a Dragon....RAWR" >> dragon.txt
 
-    - name: Upload Dragon Text FIle
+    - name: Upload Dragon Text File
       uses: actions/upload-artifact@v3
       with:
-        name: dragon-text-fIle
+        name: dragon-text-file
         path: dragon.txt
 
   test_job_2:
     needs: build_job_1
     runs-on: ubuntu-latest
     steps:
-    - name: Download Dragon Text FIle
+    - name: Download Dragon Text File
       uses: actions/download-artifact@v3
       with:
-        name: dragon-text-fIle
+        name: dragon-text-file
 
-    - name: Text File exists
-      run: grep -i "dragon" dragon.txt
+    - name: Ensure Text File Exists Before Checking
+      run: ls -l dragon.txt && grep -i "dragon" dragon.txt
 
   deploy_job_3:
-    needs: test_job_2
+    needs: [test_job_2]
     runs-on: ubuntu-latest
     steps:
-    - name: Download Dragon Text FIle
+    - name: Download Dragon Text File
       uses: actions/download-artifact@v3
       with:
-        name: dragon-text-fIle
-          
-    - name: Read File
-      run: cat dragon.txt
+        name: dragon-text-file
+
+    - name: Verify Dragon Text File Exists
+      run: test -f dragon.txt && cat dragon.txt || echo "File not found!"
 
     - name: Deploy
       run: echo "Deploying ... .. ."
